#!/bin/busybox sh
busybox mount -t proc none /proc
busybox mount -t sysfs none /sys
busybox mount -t devtmpfs none /dev

while true; do
    busybox setsid busybox cttyhack /bin/sh
    busybox sleep 1
done